### ISSUE TITLE
Downloading a new version doesn't move it to the correct directory

### ISSUE THREAD

**Issue by nouni19** [shasankp000/PyCraft#6]
I changed the selected directory, and when I downloaded a new version, it got downloaded to the default PyCraft/.minecraft and not the actual directory, it seems like an easy fix so I'll try to fix it

**Comment by shasankp000** [comment]
Hi there! I am so sorry that you still have to deal with the issues which Pycraft still has. But me and a colleague of mine are working on a new minecraft launcher which will fix all these issues, it will be launched soon, so in the meantime try checking the readme of pycraft, an updated version of it has been released by another capable coder, Try to use that in the meantime until the new launcher is released. Thanks a lot for your interest in this project!

**Comment by v-pun215** [comment]
@nouni19 I fixed that issue in my own launcher (a fork of this one), eClient. Check it out: https://github.com/v-pun215/eClient
